version: '2'
plugins:
  markdownlint:
    exclude_patterns:
      - vendor
      - LICENSE.md
    enabled: true
    checks:
      MD029:
        enabled: false
  phpcodesniffer:
    config:
      standard: "PSR1,PSR2"
    exclude_patterns:
      - "**/*"
      - "!src/*"
      - 'src/Enums/*'
    enabled: true
  phpmd:
    enabled: true
    exclude_patterns:
      - !**/*.php
    checks:
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
  duplication:
    enabled: true
exclude_patterns:
  - config/
  - 'coverage'
  - .github
  - db/
  - dist/
  - features/
  - '**/node_modules/'
  - script/
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - Tests/
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
