<?php

namespace Henzeb\Enumhancer\Tests\Unit\Laravel\Provider;


use Orchestra\Testbench\TestCase;
use Henzeb\Enumhancer\Enums\LogLevel;
use Henzeb\Enumhancer\Helpers\EnumReporter;
use Henzeb\Enumhancer\Laravel\Reporters\LaravelLogReporter;
use Henzeb\Enumhancer\Laravel\Providers\EnumhancerServiceProvider;

class EnumhancerServiceProviderTest extends TestCase
{
    public function setUp(): void
    {
        EnumReporter::set(null);
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    protected function getPackageProviders($app)
    {
        return [EnumhancerServiceProvider::class];
    }

    public function testHasSetLaravelReporter()
    {
        $this->assertEquals(
            LaravelLogReporter::class,
            EnumReporter::get()::class
        );
    }

    public function testHasSetDefaultLogLevel()
    {
        $this->assertEquals(
            LogLevel::Notice,
            LogLevel::default(),
        );
    }
}
