<?php

namespace Unit\Laravel\Provider;




use Henzeb\Enumhancer\Helpers\EnumReporter;
use Henzeb\Enumhancer\Laravel\Providers\EnumhancerServiceProvider;
use Henzeb\Enumhancer\Laravel\Reporters\LaravelLogReporter;
use Orchestra\Testbench\TestCase;

class EnumhancerServiceProviderTest extends TestCase
{
    public function setUp(): void
    {
        EnumReporter::set(null);
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    protected function getPackageProviders($app)
    {
        return [EnumhancerServiceProvider::class];
    }

    public function testHasSetLaravelReporter() {
        $this->assertEquals(
            LaravelLogReporter::class,
            EnumReporter::get()::class
        );
    }
}
